version: '3.8'

services:
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8080:8080" # REST API service port
    environment:
      - USER_SERVICE_ENV=production # Example environment variable
    depends_on:
      - game-service
      - request-service

  request-service:
    build:
      context: ./requests-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081" # gRPC service port
      - "8082:8082" # WebSocket service port
    environment:
      - REQUEST_SERVICE_ENV=production # Example environment variable
    depends_on:
      - game-service

  game-service:
    build:
      context: ./game-service
      dockerfile: Dockerfile
    ports:
      - "50051:50051" # Map the container's port to the host
    environment:
      - GAME_SERVICE_ENV=production # Example environment variable